utxo-validator {
  // A list of blacklisted utxos: if peers use one of those to open a channel with us, we will immediately close it.
  blacklisted-utxos = [
    ""
  ]
  // When the funding transaction cannot be found in the mempool or the blockchain, we will try again after this delay.
  fetch-tx-frequency = 10 minutes
}