name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout eclair
        uses: actions/checkout@v2
        with:
          repository: acinq/eclair
          path: eclair
    
      - name: Checkout eclair-plugins
        uses: actions/checkout@v2
        with:
          path: eclair-plugins

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
        
      - name: Configure OS settings
        run: echo "fs.file-max = 1024000" | sudo tee -a /etc/sysctl.conf

      - name: Build eclair
        run: mvn package -DskipTests
        working-directory: ./eclair

      - name: Build eclair plugins
        run: mvn test-compile && mvn test
        working-directory: ./eclair-plugins
